name: S3 Parse Tag Example
on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+/*/?*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse-tag.outputs.version }}
      variant: ${{ steps.parse-tag.outputs.variant }}
      type: ${{ steps.parse-tag.outputs.type }}

    steps:
      - name: Parse Tag
        id: parse-tag
        uses: fibricheck/actions-general/parse-tag@v2
        with:
          tag: ${{ github.ref }}