name: 'Set JSON Value (S3)'
description: 'Sets a value in a JSON file on S3'

inputs:
  s3-file-path: 
    description: 'The path to the JSON file on S3 (eg: s3://this.is.an.example.com/builds/build-numbers.json)'
    required: true
    type: string

  key-selector:
    description: 'The jq key selector (eg: .versionCodes.my-build)'
    required: true
    type: string

  access-key-id: 
    description: 'The S3 access key id'
    required: true
    type: string

  secret-access-key:
    required: true
    type: string

  region:
    required: true
    type: string
    default: "eu-central-1"

  value:
    required: false
  
  string:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.access-key-id }}
        aws-secret-access-key: ${{ inputs.secret-access-key }}
        aws-region: ${{ inputs.region }}
          
    - name: Set Literal
      id: set-literal
      if: "${{ inputs.value != '' }}"
      shell: bash
      run: | 
        aws s3 cp "${{ inputs.s3-file-path }}" ./s3-in-info.json || echo "{}" > s3-in-info.json
        jq "${{ inputs.key-selector }}=${{ inputs.value }}" s3-in-info.json > s3-in-info.tmp
        mv s3-in-info.tmp s3-in-info.json
        aws s3 cp s3-in-info.json "${{ inputs.s3-file-path }}"

    - name: Set String
      id: set-string
      if: "${{ inputs.string != '' }}"
      shell: bash
      run: | 
        aws s3 cp "${{ inputs.s3-file-path }}" ./s3-in-info.json || echo "{}" > s3-in-info.json
        jq "${{ inputs.key-selector }}=\"${{ inputs.string }}\"" s3-in-info.json > s3-in-info.tmp
        mv s3-in-info.tmp s3-in-info.json
        aws s3 cp s3-in-info.json "${{ inputs.s3-file-path }}"
