name: S3 Set JSON Value Example

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Set Value
        id: set-value
        uses: fibricheck/actions-general/s3-set@v2
        with:
          s3-file-path: 's3://example.fibricheck.com/example/example.json'
          key-selector: '.appVersionName.example'
          access-key-id: ${{ vars.AWS_S3_BUILDS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_BUILDS_SECRET_ACCESS_KEY }}
          value: "test"