name: SDK Version Parse Example

on:
  workflow_call:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: SDK Version Parse
        id: sdk-version-parse
        uses: fibricheck/actions-general/sdk-version-parse@v1
        with:
          version: 'v2.13.0-dev.10'
      
      - run: |
          echo "Major: ${{ steps.sdk-version-parse.outputs.major }}"
          echo "Minor: ${{ steps.sdk-version-parse.outputs.minor }}"
          echo "Patch: ${{ steps.sdk-version-parse.outputs.patch }}"
          echo "Name: ${{ steps.sdk-version-parse.outputs.name }}"
          echo "Increment: ${{ steps.sdk-version-parse.outputs.increment }}"