name: SDK Release Example

on:
  workflow_call:

jobs:
  sdk-release-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: sdk-release-dev
        id: sdk-release-dev
        uses: fibricheck/actions-general/sdk-release@v5
        with:
          token: ${{ github.token }}
          type: dev