name: 'Increment (S3)'
description: 'Increments and returns a number in a json file on S3'

inputs:
  s3-file-path: 
    description: 'The path to the JSON file on S3 (eg: s3://this.is.an.example.com/builds/build-numbers.json)'
    required: true
    type: string

  key-selector:
    description: 'The jq key selector (eg: .versionCodes.my-build)'
    required: true
    type: string

  access-key-id: 
    description: 'The S3 access key id'
    required: true
    type: string

  secret-access-key:
    required: true
    type: string

  region:
    required: true
    type: string
    default: "eu-central-1"

outputs:
  old-number:
    description: "The number before increment"
    value: ${{ steps.increment-number.outputs.old-number }}

  new-number:
    description: "The number after increment"
    value: ${{ steps.increment-number.outputs.new-number }}

runs:
  using: "composite"
  steps:
    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.access-key-id }}
        aws-secret-access-key: ${{ inputs.secret-access-key }}
        aws-region: ${{ inputs.region }}
          
    - name: Get & Increment Number
      id: increment-number
      shell: bash
      run: | 
        aws s3 cp "${{ inputs.s3-file-path }}" ./s3-in-info.json || echo "{}" > s3-in-info.json
        OLD_NUMBER=$(jq '${{ inputs.key-selector }} // 0' s3-in-info.json)
        NEW_NUMBER=$(( $OLD_NUMBER + 1 ))
        jq "${{ inputs.key-selector }}=$NEW_NUMBER" s3-in-info.json > s3-in-info.tmp
        mv s3-in-info.tmp s3-in-info.json
        aws s3 cp s3-in-info.json "${{ inputs.s3-file-path }}"
        echo "old-number=$OLD_NUMBER" >> $GITHUB_OUTPUT
        echo "new-number=$NEW_NUMBER" >> $GITHUB_OUTPUT
