name: Test S3 Increment

on:
  workflow_call:

jobs: 
  test-s3:
    runs-on: ubuntu-latest
    steps:
      - name: s3-test
        id: s3-test
        uses: ./s3-increment
        with:
            s3-file-path: ${{ vars.TEST_S3_FILE_PATH }}
            key-selector: ${{ vars.TEST_S3_KEY_SELECTOR }}
            access-key-id: ${{ vars.TEST_S3_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.TEST_S3_SECRET_ACCESS_KEY }}

      - name: verify
        run: |
            [ "${{ steps.s3-test.outputs.new-build-number }}" = "${{ github.run_number }}" ]